# Generated by Django 4.2 on 2023-06-03 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Email',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(max_length=69)),
                ('to_field', models.CharField(blank=True, max_length=100, null=True)),
                ('type', models.CharField(choices=[('DESIGN', "Drag'n'drop designed email"), ('RAW', 'Basic WYSIWYG raw text email')], max_length=6)),
                ('raw_html', models.TextField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SenderDomain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(max_length=75, unique=True)),
                ('status', models.CharField(choices=[('NONE', 'Domain needs validation'), ('VERIFIED', 'Domain has been verified'), ('WAITING', 'Domain nameis  yet to be verified')], default='NONE', max_length=10)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SenderEmail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('email_address', models.EmailField(max_length=100)),
                ('name', models.CharField(max_length=50)),
                ('reply_to', models.EmailField(max_length=100)),
                ('status', models.CharField(choices=[('VERIFIED', 'Email address can be used as sender'), ('WAITING', 'Email address needs yet to be verified')], default='WAITING', max_length=10)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
