# Generated by Django 4.0 on 2023-04-01 19:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('commons', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_set', to='users.customuser'),
        ),
        migrations.AddField(
            model_name='tag',
            name='edit_history',
            field=models.ManyToManyField(blank=True, to='commons.History'),
        ),
        migrations.AddField(
            model_name='tag',
            name='workspace',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.workspace'),
        ),
        migrations.AddField(
            model_name='history',
            name='edited_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.customuser'),
        ),
        migrations.AddField(
            model_name='exporthistory',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_set', to='users.customuser'),
        ),
        migrations.AddField(
            model_name='exporthistory',
            name='edit_history',
            field=models.ManyToManyField(blank=True, to='commons.History'),
        ),
        migrations.AddField(
            model_name='exporthistory',
            name='workspace',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.workspace'),
        ),
    ]
