# Generated by Django 4.0 on 2023-04-01 19:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('commons', '0002_initial'),
        ('users', '0001_initial'),
        ('contacts', '0002_initial'),
        ('trackerapi', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='trackerapikey',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_set', to='users.customuser'),
        ),
        migrations.AddField(
            model_name='trackerapikey',
            name='edit_history',
            field=models.ManyToManyField(blank=True, to='commons.History'),
        ),
        migrations.AddField(
            model_name='trackerapikey',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='api_keys', to='users.customuser'),
        ),
        migrations.AddField(
            model_name='trackerapikey',
            name='workspace',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.workspace'),
        ),
        migrations.AddField(
            model_name='page',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_set', to='users.customuser'),
        ),
        migrations.AddField(
            model_name='page',
            name='edit_history',
            field=models.ManyToManyField(blank=True, to='commons.History'),
        ),
        migrations.AddField(
            model_name='page',
            name='viewed_by_contact',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pages', to='contacts.contact'),
        ),
        migrations.AddField(
            model_name='page',
            name='workspace',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.workspace'),
        ),
        migrations.AddField(
            model_name='event',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_set', to='users.customuser'),
        ),
        migrations.AddField(
            model_name='event',
            name='edit_history',
            field=models.ManyToManyField(blank=True, to='commons.History'),
        ),
        migrations.AddField(
            model_name='event',
            name='triggered_by_contact',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='contacts.contact'),
        ),
        migrations.AddField(
            model_name='event',
            name='workspace',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.workspace'),
        ),
    ]
