# Generated by Django 4.0 on 2023-04-01 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AwsSes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='SES', max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Smtp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.CharField(choices=[('SES', 'Amazon Web Service SES'), ('SMTP', 'Custom SMTP Provider')], max_length=4)),
            ],
        ),
    ]
