# Generated by Django 4.2 on 2023-06-03 14:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Campaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(max_length=89)),
                ('description', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('DRAFT', 'Campaign is in Draft'), ('TO VALIDATE', 'Campaign to validate'), ('SENDING', 'Campaign being sent'), ('SCHEDULED', 'Campaign scheduled'), ('SENT', 'Campaign sent')], default='DRAFT', max_length=15)),
                ('to_type', models.CharField(blank=True, choices=[('LIST', 'Send to a list'), ('SEGMENT', 'Send to a segment')], max_length=10, null=True)),
                ('subject', models.TextField(blank=True, null=True)),
                ('scheduled_at', models.DateTimeField(blank=True, null=True)),
                ('flatten_sending', models.BooleanField(default=False)),
                ('flatten_start_time', models.DateTimeField(blank=True, null=True)),
                ('flatten_end_time', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CampaignActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('action_type', models.CharField(choices=[('SENT', 'The email was sent'), ('OPEN', 'The email was open'), ('CLICK', 'The email was clicked'), ('UNSUB', 'The contact unsubscribed from the list'), ('SPAM', 'The contact marked the campaign as spam'), ('BOUNC', 'The email bounced')], max_length=5)),
                ('details', models.TextField(blank=True, null=True)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='campaigns.campaign')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
