# Generated by Django 4.0 on 2023-04-01 20:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('emails', '0002_initial'),
        ('users', '0001_initial'),
        ('contacts', '0002_initial'),
        ('commons', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Campaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(max_length=89)),
                ('description', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('DRAFT', 'Campaign is in Draft'), ('TO VALIDATE', 'Campaign to validate'), ('SENDING', 'Campaign being sent'), ('SCHEDULED', 'Campaign scheduled'), ('SENT', 'Campaign sent')], default='DRAFT', max_length=15)),
                ('to_type', models.CharField(blank=True, choices=[('LIST', 'Send to a list'), ('SEGMENT', 'Send to a segment')], max_length=10, null=True)),
                ('subject', models.TextField(blank=True, null=True)),
                ('scheduled_at', models.DateTimeField(blank=True, null=True)),
                ('flatten_sending', models.BooleanField(default=False)),
                ('flatten_start_time', models.DateTimeField(blank=True, null=True)),
                ('flatten_end_time', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_set', to='users.customuser')),
                ('edit_history', models.ManyToManyField(blank=True, to='commons.History')),
                ('email_model', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='emails.email')),
                ('sender', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='emails.senderemail')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CampaignActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('action_type', models.CharField(choices=[('SENT', 'The email was sent'), ('OPEN', 'The email was open'), ('CLICK', 'The email was clicked'), ('UNSUB', 'The contact unsubscribed from the list'), ('SPAM', 'The contact marked the campaign as spam'), ('BOUNC', 'The email bounced')], max_length=5)),
                ('details', models.TextField(blank=True, null=True)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='campaigns.campaign')),
                ('contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contacts.contact')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_set', to='users.customuser')),
                ('edit_history', models.ManyToManyField(blank=True, to='commons.History')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.workspace')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='campaign',
            name='stats',
            field=models.ManyToManyField(through='campaigns.CampaignActivity', to='contacts.Contact'),
        ),
        migrations.AddField(
            model_name='campaign',
            name='tags',
            field=models.ManyToManyField(blank=True, to='commons.Tag'),
        ),
        migrations.AddField(
            model_name='campaign',
            name='to_list',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contacts.list'),
        ),
        migrations.AddField(
            model_name='campaign',
            name='to_segment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contacts.segment'),
        ),
        migrations.AddField(
            model_name='campaign',
            name='workspace',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.workspace'),
        ),
    ]
