# Generated by Django 4.2 on 2023-06-03 14:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ('users', '0001_initial'),
        ('commons', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('emails', '0001_initial'),
        ('campaigns', '0002_initial'),
        ('contacts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaignactivity',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL,
                                    related_name='%(class)s_set', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='campaignactivity',
            name='edit_history',
            field=models.ManyToManyField(blank=True, to='commons.history'),
        ),
        migrations.AddField(
            model_name='campaignactivity',
            name='email',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='emails.email'),
        ),
        migrations.AddField(
            model_name='campaignactivity',
            name='workspace',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.workspace'),
        ),
        migrations.AddField(
            model_name='campaign',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL,
                                    related_name='%(class)s_set', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='campaign',
            name='edit_history',
            field=models.ManyToManyField(blank=True, to='commons.history'),
        ),
        migrations.AddField(
            model_name='campaign',
            name='email_model',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE,
                                    to='emails.email'),
        ),
        migrations.AddField(
            model_name='campaign',
            name='sender',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE,
                                    to='emails.senderemail'),
        ),
        migrations.AddField(
            model_name='campaign',
            name='stats',
            field=models.ManyToManyField(through='campaigns.CampaignActivity', to='contacts.contact'),
        ),
        migrations.AddField(
            model_name='campaign',
            name='tags',
            field=models.ManyToManyField(blank=True, to='commons.tag'),
        ),
        migrations.AddField(
            model_name='campaign',
            name='to_list',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE,
                                    to='contacts.list'),
        ),
        migrations.AddField(
            model_name='campaign',
            name='to_segment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE,
                                    to='contacts.segment'),
        ),
        migrations.AddField(
            model_name='campaign',
            name='workspace',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.workspace'),
        ),
    ]
