# Generated by Django 4.2 on 2023-05-26 18:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ('emails', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('commons', '0002_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AutomationCampaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(max_length=89)),
                ('description', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('DRAFT', 'Automation campaign is in Draft.'), (
                'ACTIVE', 'Automation campaign is active and emails are being sent.'),
                                                     ('PAUSED', 'Automation campaign is stopped.')], default='DRAFT',
                                            max_length=15)),
                ('is_repeated', models.BooleanField(default=True)),
                ('trigger', models.JSONField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL,
                                                 related_name='%(class)s_set', to=settings.AUTH_USER_MODEL)),
                ('edit_history', models.ManyToManyField(blank=True, to='commons.history')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Step',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('order', models.IntegerField(default=0)),
                ('step_type', models.CharField(
                    choices=[('SEND_EMAIL', 'Send an email when the Contact enters this Step.'),
                             ('WAIT', 'Wait for a specific time before processing the next Step.'), ('CONDITION', '')],
                    default='SEND_EMAIL', max_length=15)),
                ('automation_campaign',
                 models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE,
                                   to='automation.automationcampaign')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL,
                                                 related_name='%(class)s_set', to=settings.AUTH_USER_MODEL)),
                ('edit_history', models.ManyToManyField(blank=True, to='commons.history')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.workspace')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='StepWait',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('delay', models.IntegerField(default=1)),
                ('delay_unit',
                 models.CharField(choices=[('DAY', 'Day'), ('HOUR', 'Hour'), ('WEEK', 'Week')], default='DAY',
                                  max_length=15)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL,
                                                 related_name='%(class)s_set', to=settings.AUTH_USER_MODEL)),
                ('edit_history', models.ManyToManyField(blank=True, to='commons.history')),
                ('step', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE,
                                              related_name='wait_step', to='automation.step')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.workspace')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='StepSendEmail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL,
                                                 related_name='%(class)s_set', to=settings.AUTH_USER_MODEL)),
                ('edit_history', models.ManyToManyField(blank=True, to='commons.history')),
                ('email', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE,
                                            to='emails.email')),
                ('step', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE,
                                              related_name='send_email_step', to='automation.step')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.workspace')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='AutomationCampaignContact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL,
                                                 related_name='%(class)s_set', to=settings.AUTH_USER_MODEL)),
                ('edit_history', models.ManyToManyField(blank=True, to='commons.history')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.workspace')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='automationcampaign',
            name='steps',
            field=models.ManyToManyField(blank=True, to='automation.step'),
        ),
        migrations.AddField(
            model_name='automationcampaign',
            name='workspace',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.workspace'),
        ),
    ]
