# Generated by Django 4.2 on 2023-06-03 14:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ('users', '0001_initial'),
        ('commons', '0001_initial'),
        ('automation', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('emails', '0001_initial'),
        ('contacts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='triggertime',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL,
                                    related_name='%(class)s_set', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='triggertime',
            name='edit_history',
            field=models.ManyToManyField(blank=True, to='commons.history'),
        ),
        migrations.AddField(
            model_name='triggertime',
            name='workspace',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.workspace'),
        ),
        migrations.AddField(
            model_name='triggersegment',
            name='automation_campaign',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE,
                                       related_name='segment_trigger', to='automation.automationcampaign'),
        ),
        migrations.AddField(
            model_name='triggersegment',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL,
                                    related_name='%(class)s_set', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='triggersegment',
            name='edit_history',
            field=models.ManyToManyField(blank=True, to='commons.history'),
        ),
        migrations.AddField(
            model_name='triggersegment',
            name='segment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE,
                                    to='contacts.segment'),
        ),
        migrations.AddField(
            model_name='triggersegment',
            name='workspace',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.workspace'),
        ),
        migrations.AddField(
            model_name='triggerpage',
            name='automation_campaign',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE,
                                       related_name='page_trigger', to='automation.automationcampaign'),
        ),
        migrations.AddField(
            model_name='triggerpage',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL,
                                    related_name='%(class)s_set', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='triggerpage',
            name='edit_history',
            field=models.ManyToManyField(blank=True, to='commons.history'),
        ),
        migrations.AddField(
            model_name='triggerpage',
            name='workspace',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.workspace'),
        ),
        migrations.AddField(
            model_name='triggerlist',
            name='automation_campaign',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE,
                                       related_name='list_trigger', to='automation.automationcampaign'),
        ),
        migrations.AddField(
            model_name='triggerlist',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL,
                                    related_name='%(class)s_set', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='triggerlist',
            name='edit_history',
            field=models.ManyToManyField(blank=True, to='commons.history'),
        ),
        migrations.AddField(
            model_name='triggerlist',
            name='list',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE,
                                    to='contacts.list'),
        ),
        migrations.AddField(
            model_name='triggerlist',
            name='workspace',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.workspace'),
        ),
        migrations.AddField(
            model_name='triggerevent',
            name='automation_campaign',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE,
                                       related_name='event_trigger', to='automation.automationcampaign'),
        ),
        migrations.AddField(
            model_name='triggerevent',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL,
                                    related_name='%(class)s_set', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='triggerevent',
            name='edit_history',
            field=models.ManyToManyField(blank=True, to='commons.history'),
        ),
        migrations.AddField(
            model_name='triggerevent',
            name='workspace',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.workspace'),
        ),
        migrations.AddField(
            model_name='triggeremail',
            name='automation_campaign',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE,
                                       related_name='email_trigger', to='automation.automationcampaign'),
        ),
        migrations.AddField(
            model_name='triggeremail',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL,
                                    related_name='%(class)s_set', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='triggeremail',
            name='edit_history',
            field=models.ManyToManyField(blank=True, to='commons.history'),
        ),
        migrations.AddField(
            model_name='triggeremail',
            name='email',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE,
                                    to='emails.email'),
        ),
        migrations.AddField(
            model_name='triggeremail',
            name='workspace',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.workspace'),
        ),
        migrations.AddField(
            model_name='stepwait',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL,
                                    related_name='%(class)s_set', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='stepwait',
            name='edit_history',
            field=models.ManyToManyField(blank=True, to='commons.history'),
        ),
        migrations.AddField(
            model_name='stepwait',
            name='step',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE,
                                       related_name='wait_step', to='automation.step'),
        ),
        migrations.AddField(
            model_name='stepwait',
            name='workspace',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.workspace'),
        ),
        migrations.AddField(
            model_name='stepsendemail',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL,
                                    related_name='%(class)s_set', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='stepsendemail',
            name='edit_history',
            field=models.ManyToManyField(blank=True, to='commons.history'),
        ),
        migrations.AddField(
            model_name='stepsendemail',
            name='email',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE,
                                    to='emails.email'),
        ),
        migrations.AddField(
            model_name='stepsendemail',
            name='step',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE,
                                       related_name='send_email_step', to='automation.step'),
        ),
        migrations.AddField(
            model_name='stepsendemail',
            name='workspace',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.workspace'),
        ),
        migrations.AddField(
            model_name='step',
            name='automation_campaign',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE,
                                    to='automation.automationcampaign'),
        ),
        migrations.AddField(
            model_name='step',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL,
                                    related_name='%(class)s_set', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='step',
            name='edit_history',
            field=models.ManyToManyField(blank=True, to='commons.history'),
        ),
        migrations.AddField(
            model_name='step',
            name='workspace',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.workspace'),
        ),
        migrations.AddField(
            model_name='automationcampaigncontact',
            name='automation_campaign',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE,
                                    to='automation.automationcampaign'),
        ),
        migrations.AddField(
            model_name='automationcampaigncontact',
            name='contact',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE,
                                    to='contacts.contact'),
        ),
        migrations.AddField(
            model_name='automationcampaigncontact',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL,
                                    related_name='%(class)s_set', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='automationcampaigncontact',
            name='current_step',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE,
                                    to='automation.step'),
        ),
        migrations.AddField(
            model_name='automationcampaigncontact',
            name='edit_history',
            field=models.ManyToManyField(blank=True, to='commons.history'),
        ),
        migrations.AddField(
            model_name='automationcampaigncontact',
            name='workspace',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.workspace'),
        ),
        migrations.AddField(
            model_name='automationcampaign',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL,
                                    related_name='%(class)s_set', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='automationcampaign',
            name='current_contacts',
            field=models.ManyToManyField(blank=True, through='automation.AutomationCampaignContact',
                                         to='contacts.contact'),
        ),
        migrations.AddField(
            model_name='automationcampaign',
            name='done_contacts',
            field=models.ManyToManyField(blank=True, related_name='done_automation_campaigns', to='contacts.contact'),
        ),
        migrations.AddField(
            model_name='automationcampaign',
            name='edit_history',
            field=models.ManyToManyField(blank=True, to='commons.history'),
        ),
        migrations.AddField(
            model_name='automationcampaign',
            name='steps',
            field=models.ManyToManyField(blank=True, to='automation.step'),
        ),
        migrations.AddField(
            model_name='automationcampaign',
            name='workspace',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.workspace'),
        ),
    ]
